# cesi/nginx
FROM cesi/base
MAINTAINER Michael Behlendorf <michael.behlendorf@triology.de>

# dockerfile is based on https://github.com/dockerfile/nginx and https://github.com/bellycard/docker-loadbalancer

ENV NGINX_VERSION nginx-1.9.9

# VOLUMES
VOLUME ["/resources"]
ADD build.sh /build.sh
RUN chmod +x /build.sh

CMD /build.sh
