<?xml version="1.0" encoding="UTF-8"?>
<security>
  <version>2.0.5</version>
  <users>
    <user>
      <id>deployment</id>
      <firstName>Deployment</firstName>
      <lastName>User</lastName>
      <password>b2a0e378437817cebdf753d7dff3dd75483af9e0</password>
      <status>active</status>
      <email>changeme1@yourcompany.com</email>
    </user>
    <user>
      <id>admin</id>
      <firstName>Administrator</firstName>
      <lastName>User</lastName>
      <password>$shiro1$SHA-512$1024$hrky0OntSzjdPL62bR4V1g==$EbJgkw57FXbsTqfraHJpbW2lCLzfgpJ60PZDxtF1AcUZIqKtsZH1LpGzqtD47AhGMN0gKeh3rzJbM38vxNZnFw==</password>
      <status>active</status>
      <email>changeme@yourcompany.com</email>
    </user>
    <user>
      <id>anonymous</id>
      <firstName>Nexus</firstName>
      <lastName>Anonymous User</lastName>
      <password>0a92fab3230134cca6eadd9898325b9b2ae67998</password>
      <status>disabled</status>
      <email>changeme2@yourcompany.com</email>
    </user>
  </users>
  <roles>
    <role>
      <id>$ADMINGROUP</id>
      <name>$ADMINGROUP</name>
      <description>$ADMINGROUP</description>
      <roles>
        <role>nx-admin</role>
      </roles>
    </role>
  </roles>
  <userRoleMappings>
    <userRoleMapping>
      <userId>deployment</userId>
      <source>default</source>
      <roles>
        <role>nx-deployment</role>
        <role>repository-any-full</role>
      </roles>
    </userRoleMapping>
    <userRoleMapping>
      <userId>admin</userId>
      <source>default</source>
      <roles>
        <role>nx-admin</role>
      </roles>
    </userRoleMapping>
    <userRoleMapping>
      <userId>anonymous</userId>
      <source>default</source>
      <roles>
        <role>repository-any-read</role>
        <role>anonymous</role>
      </roles>
    </userRoleMapping>
  </userRoleMappings>
</security>
