# registry.cloudogu.com/official/nodejs
FROM registry.cloudogu.com/official/base:3.3-1
MAINTAINER christoph wolfes <christoph.wolfes@triology.de>

#install newest nodejs version
#currently used version 4.4.3 (compare https://goo.gl/jGZR3x accessed 14.4.16)

RUN apk add --update nodejs
